name: Main Workflow
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  cicd:
    name: Deploy using aws eks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure temporary AWS credentials
      uses: aws-actions/configure-aws-credentials@v6.1.0
      with:
        role-to-assume: arn:aws:iam::416338226474:role/Github_action_role_02.08
        role-session-name: github-actions-${{ github.run_id }}
        aws-region: us-west-2
    
    - name: Confirm aws credentials
      run: |
        aws sts get-caller-identity
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
                
    - name: Build,tag & push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: myapps/pacman
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./docker
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Configure eks access
      run: |
        aws eks update-kubeconfig --region us-west-2 --name pacman-cluster

    - name: EKS deployment
      run: |
        kubectl apply -f ./k8s/storage-class.yaml
        kubectl apply -f ./k8s/db-sts.yaml  
        kubectl apply -f ./k8s/app-deployment.yaml
        kubectl set image deployment/pacman-app pacman=416338226474.dkr.ecr.us-west-2.amazonaws.com/myapps/pacman:${{ github.sha }}
        kubectl rollout status deployment pacman-app
        kubectl rollout status statefulset mongo
        kubectl get services pacman-service
